-- =============================================================
-- 0003_seed.sql  —  DML: realistic seed data
-- CMPE344 Database Management Systems and Programming II
--
-- Demo password for every account: Passw0rd!
-- The hash below is a real bcrypt (cost 12) digest, generated by
-- src/auth.py's hashing routine — not a placeholder string.
-- =============================================================

BEGIN;

-- -------------------------------------------------------------
-- Roles — the "user groups" the brief requires
-- -------------------------------------------------------------
INSERT INTO roles (role_name, description, access_level) VALUES
    ('admin',     'Full system access. Manages users, roles and all records.', 5),
    ('registrar', 'Student records, enrolment and reporting. No user management.', 4),
    ('instructor','Manages own course sections, assignments and grading.',         3),
    ('student',   'Views own enrolments, grades and attendance. Read only.',       1),
    ('technical', 'Maintains classrooms, timetables and infrastructure.',         2);

-- -------------------------------------------------------------
-- Departments
-- -------------------------------------------------------------
INSERT INTO departments (dept_code, dept_name, annual_budget, established_year) VALUES
    ('CS', 'Computer Science',       1850000.00, 1998),
    ('EE', 'Electrical Engineering', 1620000.00, 2001),
    ('ME', 'Mechanical Engineering', 1480000.00, 2003),
    ('BA', 'Business Administration', 940000.00, 1995),
    ('PS', 'Psychology',              720000.00, 2008),
    ('MA', 'Mathematics',             810000.00, 1992);

-- -------------------------------------------------------------
-- Classrooms
-- -------------------------------------------------------------
INSERT INTO classrooms (building, room_number, capacity, has_projector) VALUES
    ('Science',   'A101', 60, TRUE),  ('Science',   'A102', 40, TRUE),
    ('Science',   'B204', 35, FALSE), ('Engineering','E301', 45, TRUE),
    ('Engineering','E305', 25, FALSE),('Business',  'C110', 80, TRUE),
    ('Humanities','H201', 50, FALSE),('Library',   'L002', 30, TRUE);

-- -------------------------------------------------------------
-- Staff and admin accounts
-- -------------------------------------------------------------
INSERT INTO users (username, email, password_hash, first_name, last_name, status) VALUES
    ('admin',    'admin@school.edu',    '$2b$12$4f7v9UCLth6kmWV64vzWBudhI9uebdOTNeIPCUXpZyNb9gBHvWt/u', 'System',    'Administrator', 'active'),
    ('registrar','registrar@school.edu','$2b$12$4f7v9UCLth6kmWV64vzWBudhI9uebdOTNeIPCUXpZyNb9gBHvWt/u', 'Elif',      'Yildirim',      'active'),
    ('i.kaya',   'i.kaya@school.edu',   '$2b$12$4f7v9UCLth6kmWV64vzWBudhI9uebdOTNeIPCUXpZyNb9gBHvWt/u', 'Mert',      'Kaya',          'active'),
    ('i.demir',  'i.demir@school.edu',  '$2b$12$4f7v9UCLth6kmWV64vzWBudhI9uebdOTNeIPCUXpZyNb9gBHvWt/u', 'Seda',      'Demir',         'active'),
    ('i.ozturk', 'i.ozturk@school.edu', '$2b$12$4f7v9UCLth6kmWV64vzWBudhI9uebdOTNeIPCUXpZyNb9gBHvWt/u', 'Burak',     'Ozturk',        'active'),
    ('i.acar',   'i.acar@school.edu',   '$2b$12$4f7v9UCLth6kmWV64vzWBudhI9uebdOTNeIPCUXpZyNb9gBHvWt/u', 'Deniz',     'Acar',          'active'),
    ('i.koc',    'i.koc@school.edu',    '$2b$12$4f7v9UCLth6kmWV64vzWBudhI9uebdOTNeIPCUXpZyNb9gBHvWt/u', 'Aylin',     'Koc',           'active'),
    ('i.sahin',  'i.sahin@school.edu',  '$2b$12$4f7v9UCLth6kmWV64vzWBudhI9uebdOTNeIPCUXpZyNb9gBHvWt/u', 'Cem',       'Sahin',         'active');

-- -------------------------------------------------------------
-- 25 student accounts, generated rather than hand-listed
-- -------------------------------------------------------------
INSERT INTO users (username, email, password_hash, first_name, last_name, status)
SELECT
    'student' || g,
    'student' || g || '@school.edu',
    '$2b$12$4f7v9UCLth6kmWV64vzWBudhI9uebdOTNeIPCUXpZyNb9gBHvWt/u',
    (ARRAY['Ali','Ayse','Mehmet','Zeynep','Can','Elif','Emre','Deniz','Burak','Ceren',
           'Kerem','Selin','Baris','Melis','Onur','Sena','Kaan','Duru','Arda','Pelin',
           'Efe','Neha','Kaya','Su','Bora'])[g],
    (ARRAY['Yilmaz','Kaya','Demir','Sahin','Aydin','Celik','Yildiz','Yilmaz','Ozturk','Arslan',
           'Koc','Kurt','Acar','Duman','Tekin','Eren','Gunes','Yavuz','Polat','Sah',
           'Akin','Karakaya','Bal','Turan','Aksoy'])[g],
    'active'
FROM generate_series(1, 25) AS g;

-- -------------------------------------------------------------
-- Role assignments
-- -------------------------------------------------------------
INSERT INTO user_roles (user_id, role_id)
SELECT u.user_id, r.role_id FROM users u, roles r
WHERE u.username = 'admin'      AND r.role_name = 'admin'
UNION ALL
SELECT u.user_id, r.role_id FROM users u, roles r
WHERE u.username = 'registrar'  AND r.role_name = 'registrar'
UNION ALL
SELECT u.user_id, r.role_id FROM users u, roles r
WHERE u.username LIKE 'i.%'      AND r.role_name = 'instructor'
UNION ALL
SELECT u.user_id, r.role_id FROM users u, roles r
WHERE u.username LIKE 'student%' AND r.role_name = 'student';

-- The brief asks for role *groups*; giving one member two roles
-- demonstrates the user_roles join table is genuinely many-to-many.
INSERT INTO user_roles (user_id, role_id)
SELECT u.user_id, r.role_id FROM users u, roles r
WHERE u.username = 'i.koc' AND r.role_name = 'technical';

-- -------------------------------------------------------------
-- Instructor profiles
-- -------------------------------------------------------------
INSERT INTO instructors (user_id, department_id, employee_no, hire_date, rank_title, salary)
SELECT
    (SELECT user_id FROM users WHERE username = v.username),
    (SELECT department_id FROM departments WHERE dept_code = v.dept),
    v.empno, v.hired, v.title, v.pay
FROM (VALUES
    ('i.kaya',   'CS', 'E-1001', DATE '2015-09-01', 'Professor',      96000.00),
    ('i.demir',  'EE', 'E-1002', DATE '2018-02-15', 'Associate Prof', 78000.00),
    ('i.ozturk', 'ME', 'E-1003', DATE '2020-09-01', 'Lecturer',       62000.00),
    ('i.acar',   'BA', 'E-1004', DATE '2017-03-20', 'Professor',      91000.00),
    ('i.koc',    'PS', 'E-1005', DATE '2021-09-01', 'Lecturer',       60000.00),
    ('i.sahin',  'MA', 'E-1006', DATE '2013-09-01', 'Professor',      99000.00)
) AS v(username, dept, empno, hired, title, pay);

-- -------------------------------------------------------------
-- Student profiles
-- -------------------------------------------------------------
INSERT INTO students (user_id, department_id, student_no, program_level, enrollment_year, gpa)
SELECT
    (SELECT user_id FROM users WHERE username = 'student' || v.g),
    (SELECT department_id FROM departments WHERE dept_code = v.dept),
    'S-' || LPAD(v.g::TEXT, 5, '0'),
    v.lvl::program_level,
    v.yr,
    0.00
FROM (VALUES
    (1,'CS','undergraduate',2023),(2,'CS','undergraduate',2023),(3,'CS','graduate',2022),
    (4,'EE','undergraduate',2024),(5,'EE','undergraduate',2023),(6,'EE','graduate',2021),
    (7,'ME','undergraduate',2024),(8,'ME','undergraduate',2023),(9,'ME','undergraduate',2022),
    (10,'BA','undergraduate',2024),(11,'BA','undergraduate',2023),(12,'BA','undergraduate',2022),
    (13,'PS','undergraduate',2024),(14,'PS','undergraduate',2023),(15,'PS','graduate',2022),
    (16,'MA','undergraduate',2023),(17,'MA','undergraduate',2022),(18,'MA','graduate',2021),
    (19,'CS','undergraduate',2024),(20,'CS','undergraduate',2024),(21,'EE','undergraduate',2024),
    (22,'ME','undergraduate',2024),(23,'BA','undergraduate',2024),(24,'PS','undergraduate',2024),
    (25,'MA','undergraduate',2024)
) AS v(g, dept, lvl, yr);

-- Advisors: every student in year >= 2023 is advised by a
-- graduate student from the same department. EXISTS is used
-- instead of joining the target table, because an UPDATE cannot
-- reference its own table inside a FROM-join condition.
UPDATE students s
   SET advisor_id = (
       SELECT a.student_id
         FROM students a
         JOIN users au ON au.user_id = a.user_id
        WHERE a.program_level = 'graduate'
          AND a.student_id <> s.student_id
          AND au.username = 'student' || a.student_id::TEXT
          AND a.department_id = s.department_id
        ORDER BY a.student_id
        LIMIT 1
   )
 WHERE s.enrollment_year >= 2023
   AND s.student_id % 3 <> 0;

-- -------------------------------------------------------------
-- Course sections — one row per offering, so the same course code
-- appears more than once with a different instructor or room.
-- -------------------------------------------------------------
INSERT INTO course_sections
    (course_code, course_name, term, academic_year, instructor_id, classroom_id, credits, capacity)
VALUES
    ('CS301', 'Database Systems',        'Spring', 2025, (SELECT instructor_id FROM instructors WHERE employee_no='E-1001'), (SELECT classroom_id FROM classrooms WHERE building='Science' AND room_number='A101'), 4, 55),
    ('CS302', 'Web Technologies',       'Spring', 2025, (SELECT instructor_id FROM instructors WHERE employee_no='E-1001'), (SELECT classroom_id FROM classrooms WHERE building='Science' AND room_number='A102'), 3, 40),
    ('CS401', 'Machine Learning',        'Spring', 2025, (SELECT instructor_id FROM instructors WHERE employee_no='E-1001'), (SELECT classroom_id FROM classrooms WHERE building='Science' AND room_number='A102'), 4, 30),
    ('EE201', 'Circuit Analysis',        'Spring', 2025, (SELECT instructor_id FROM instructors WHERE employee_no='E-1002'), (SELECT classroom_id FROM classrooms WHERE building='Engineering' AND room_number='E301'), 4, 45),
    ('EE305', 'Embedded Systems',        'Spring', 2025, (SELECT instructor_id FROM instructors WHERE employee_no='E-1002'), (SELECT classroom_id FROM classrooms WHERE building='Engineering' AND room_number='E305'), 3, 25),
    ('ME210', 'Thermodynamics',          'Spring', 2025, (SELECT instructor_id FROM instructors WHERE employee_no='E-1003'), (SELECT classroom_id FROM classrooms WHERE building='Engineering' AND room_number='E301'), 4, 40),
    ('ME320', 'Fluid Mechanics',         'Spring', 2025, (SELECT instructor_id FROM instructors WHERE employee_no='E-1003'), (SELECT classroom_id FROM classrooms WHERE building='Engineering' AND room_number='E305'), 3, 25),
    ('BA110', 'Principles of Marketing', 'Spring', 2025, (SELECT instructor_id FROM instructors WHERE employee_no='E-1004'), (SELECT classroom_id FROM classrooms WHERE building='Business' AND room_number='C110'), 3, 75),
    ('BA250', 'Financial Accounting',    'Spring', 2025, (SELECT instructor_id FROM instructors WHERE employee_no='E-1004'), (SELECT classroom_id FROM classrooms WHERE building='Business' AND room_number='C110'), 3, 70),
    ('PS101', 'Introduction to Psychology','Spring',2025,(SELECT instructor_id FROM instructors WHERE employee_no='E-1005'), (SELECT classroom_id FROM classrooms WHERE building='Humanities' AND room_number='H201'), 3, 50),
    ('PS340', 'Cognitive Neuroscience',  'Spring', 2025, (SELECT instructor_id FROM instructors WHERE employee_no='E-1005'), (SELECT classroom_id FROM classrooms WHERE building='Humanities' AND room_number='H201'), 4, 30),
    ('MA200', 'Linear Algebra',          'Spring', 2025, (SELECT instructor_id FROM instructors WHERE employee_no='E-1006'), (SELECT classroom_id FROM classrooms WHERE building='Library' AND room_number='L002'), 3, 30),
    -- Fall 2025 offerings: still open, so enrolments have no grade
    -- and the "current term" reports have something to show.
    ('CS310', 'Operating Systems',       'Fall',   2025, (SELECT instructor_id FROM instructors WHERE employee_no='E-1001'), (SELECT classroom_id FROM classrooms WHERE building='Science' AND room_number='A101'), 4, 50),
    ('CS320', 'Software Engineering',    'Fall',   2025, (SELECT instructor_id FROM instructors WHERE employee_no='E-1001'), (SELECT classroom_id FROM classrooms WHERE building='Science' AND room_number='A102'), 3, 40),
    ('EE210', 'Signals and Systems',     'Fall',   2025, (SELECT instructor_id FROM instructors WHERE employee_no='E-1002'), (SELECT classroom_id FROM classrooms WHERE building='Engineering' AND room_number='E301'), 3, 45),
    ('BA220', 'Operations Management',   'Fall',   2025, (SELECT instructor_id FROM instructors WHERE employee_no='E-1004'), (SELECT classroom_id FROM classrooms WHERE building='Business' AND room_number='C110'), 3, 70),
    ('PS210', 'Social Psychology',       'Fall',   2025, (SELECT instructor_id FROM instructors WHERE employee_no='E-1005'), (SELECT classroom_id FROM classrooms WHERE building='Humanities' AND room_number='H201'), 3, 45),
    ('MA210', 'Calculus II',             'Fall',   2025, (SELECT instructor_id FROM instructors WHERE employee_no='E-1006'), (SELECT classroom_id FROM classrooms WHERE building='Library' AND room_number='L002'), 4, 30);

-- -------------------------------------------------------------
-- Enrolments
-- Only Spring-2025 sections get final grades; Fall-2025 sections
-- stay open. Both shapes need to exist or the reports have
-- nothing interesting to say.
-- -------------------------------------------------------------
INSERT INTO enrollments (student_id, section_id, status, final_grade, grade_letter)
SELECT
    s.student_id,
    cs.section_id,
    'completed',
    ROUND(45 + ((s.student_id * 7 + cs.section_id * 13) % 55), 2),
    NULL
FROM students s
JOIN course_sections cs
  ON cs.course_code LIKE (SELECT d.dept_code || '%' FROM departments d
                           WHERE d.department_id = s.department_id)
WHERE cs.term = 'Spring' AND cs.academic_year = 2025;

-- A handful of failing and dropped records, so the grade
-- distribution report has a spread and the app has rows to delete.
UPDATE enrollments SET final_grade = 42.50
 WHERE student_id IN (7, 19) AND section_id IN (SELECT section_id FROM course_sections WHERE course_code LIKE 'ME%');

INSERT INTO enrollments (student_id, section_id, status, final_grade, grade_letter)
SELECT s.student_id, cs.section_id, 'enrolled', NULL, NULL
FROM students s
JOIN course_sections cs
  ON cs.course_code LIKE (SELECT d.dept_code || '%' FROM departments d
                           WHERE d.department_id = s.department_id)
WHERE cs.term = 'Fall' AND cs.academic_year = 2025
  AND s.student_id <= 3;

-- Withdraw a few students by converting their existing enrolment
-- rather than inserting a second one: (student_id, section_id) is
-- unique, and the CHECK constraint requires a 'dropped' row to
-- carry no grade.
UPDATE enrollments
   SET status = 'dropped', final_grade = NULL, grade_letter = NULL
 WHERE status = 'completed'
   AND student_id IN (12, 23);

-- Populate letter grades for the seeded rows. Done by calling
-- letter_grade_for() directly rather than re-saving the score, so
-- the grade-change trigger does not fire and the audit trail stays
-- free of 50 rows of seed noise.
UPDATE enrollments
   SET grade_letter = letter_grade_for(final_grade)
 WHERE final_grade IS NOT NULL
   AND grade_letter IS NULL;

-- -------------------------------------------------------------
-- Assignments
-- -------------------------------------------------------------
INSERT INTO assignments (section_id, title, weight, max_points, due_date)
SELECT cs.section_id, v.title, v.wt, v.pts, v.due::date
FROM (VALUES
    (1,'Assignment 1 - ER Modelling',        10.00, 100.00,'2025-03-07'),
    (1,'Assignment 2 - SQL Joins',           15.00, 100.00,'2025-03-28'),
    (1,'Midterm Project - Schema Design',   30.00, 100.00,'2025-04-18'),
    (2,'Assignment 1 - HTML Forms',          10.00,  50.00,'2025-03-14'),
    (2,'Assignment 2 - REST Endpoints',      15.00, 100.00,'2025-04-04'),
    (3,'Assignment 1 - Linear Regression',   20.00, 100.00,'2025-03-21'),
    (4,'Assignment 1 - Mesh Analysis',       10.00, 100.00,'2025-03-14'),
    (5,'Assignment 1 - GPIO Drivers',        15.00,  75.00,'2025-03-21'),
    (6,'Problem Set 1',                       10.00, 100.00,'2025-03-07'),
    (7,'Problem Set 2',                       10.00, 100.00,'2025-03-28'),
    (8,'Case Study - Pricing',               20.00, 100.00,'2025-04-11'),
    (9,'Problem Set 1 - Ledgers',            15.00, 100.00,'2025-03-21'),
    (10,'Essay - Research Methods',          20.00, 100.00,'2025-04-04'),
    (11,'Assignment 1 - Perception Mapping', 15.00, 100.00,'2025-03-28'),
    (12,'Problem Set 1 - Vector Spaces',     10.00, 100.00,'2025-03-14')
) AS v(sec, title, wt, pts, due)
JOIN course_sections cs ON cs.section_id = v.sec;

-- -------------------------------------------------------------
-- Submissions — one per enrolled student per assignment.
-- Scores are skewed high so the average-vs-percentage report in
-- docs/report.md has something meaningful to show.
-- -------------------------------------------------------------
INSERT INTO submissions (assignment_id, student_id, submitted_at, score, graded_by, is_late)
SELECT
    a.assignment_id,
    e.student_id,
    a.due_date - ((e.student_id % 4) || ' days')::INTERVAL,
    CASE WHEN e.student_id % 11 = 0 THEN NULL
         ELSE ROUND((a.max_points * 0.55 + ((e.student_id * 13) % 45) / 100.0 * a.max_points), 2) END,
    (SELECT user_id FROM users WHERE username = 'admin'),
    (e.student_id % 9 = 0)
FROM assignments a
JOIN enrollments e ON e.section_id = a.section_id
WHERE e.status <> 'dropped';

-- -------------------------------------------------------------
-- Attendance — four sessions per section.
--
-- The status is drawn from a weighted distribution rather than from
-- a modulus of student_id: an expression like (student_id + day) % 7
-- correlates the outcome with the student, which produced students
-- marked absent at every single session.
--
-- The draw comes from an md5 hash of (student, date) rather than
-- random(). random() evaluated through a LATERAL subquery was
-- hoisted into a single one-time Result node, giving every row the
-- same status. A hash is per-row by construction and still
-- reproducible: re-running the seed yields identical data.
-- -------------------------------------------------------------
INSERT INTO attendance (section_id, student_id, session_date, status)
SELECT
    t.section_id,
    t.student_id,
    t.session_date,
    CASE
        WHEN t.bucket <  86 THEN 'present'   -- 86%
        WHEN t.bucket <  91 THEN 'late'      --  5%
        WHEN t.bucket <  98 THEN 'absent'    --  7%
        ELSE                   'excused'    --  2%
    END::attendance_status
FROM (
    SELECT
        e.section_id,
        e.student_id,
        d.session_date,
        abs(('x' || substr(
             md5(e.student_id::TEXT || ':' || d.session_date::TEXT), 1, 8
         ))::bit(32)::BIGINT) % 100 AS bucket
    FROM enrollments e
    CROSS JOIN (VALUES (DATE '2025-03-05'), (DATE '2025-03-12'),
                       (DATE '2025-03-19'), (DATE '2025-03-26')
              ) AS d(session_date)
    WHERE e.status <> 'dropped'
) AS t;

COMMIT;

-- -------------------------------------------------------------
-- Seed summary, so the report can quote real counts.
-- -------------------------------------------------------------
SELECT 'users'            AS entity, COUNT(*) FROM users
UNION ALL SELECT 'departments',      COUNT(*) FROM departments
UNION ALL SELECT 'instructors',      COUNT(*) FROM instructors
UNION ALL SELECT 'students',         COUNT(*) FROM students
UNION ALL SELECT 'course_sections',  COUNT(*) FROM course_sections
UNION ALL SELECT 'enrollments',      COUNT(*) FROM enrollments
UNION ALL SELECT 'assignments',      COUNT(*) FROM assignments
UNION ALL SELECT 'submissions',      COUNT(*) FROM submissions
UNION ALL SELECT 'attendance',       COUNT(*) FROM attendance;